### ISSUE TITLE
No release

### ISSUE THREAD

**Issue by MTFPLEX** [Gredwitch/Dagor-Asset-Explorer#2]
You mention an .EXE being under release, and I am unable to compile your software.
When using these arguments, I am provided with an error stating 'NoType' object has no attribute 'get_v482'.
`python3 -m PyInstaller --onefile --windowed --hidden-import PyQt5 --hidden-import pyperclip --hidden-import pylzma --hidden-import zstandard --hidden-import Pillow -p "./gui;./util;./parse" -F __main__.py -n DagorAssetExplorer`
![image](https://github.com/Gredwitch/Dagor-Asset-Explorer/assets/87290130/b364c013-540a-4fea-bbbb-735a16782394)
Full error:
`Traceback (most recent call last):
  File "__main__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "mapDialog.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "dbld.py", line 21, in <module>
AttributeError: 'NoneType' object has no attribute 'get_v482'`

**Comment by upolp** [comment]
I'm getting the same errors, did you solve this issue? Downloading the release .exe also does not work for me, same error.
